apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  type: ClusterIP
  selector:
    app: django-blue     # Initially points to blue deployment pods
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
